name: gl_dart
version: 0.2.2
description: dart:ffi bindings for OpenGL library. It connects the opengl32.dll/libgl.so library and loads the functions of the specified version of opengl.
homepage: https://github.com/armacoty/gl_dart

environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.16.0
dependencies:
  ffi: ^1.0.0
