name: gl_dart
version: 0.2.0
author: Vinogadov Alexander <armacoty@protonmail.com>
description: dart:ffi bindings for OpenGL library. It connects the opengl32.dll/libgl.so library and loads the functions of the specified version of opengl.
homepage: https://github.com/armacoty/gl_dart

environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.12.0
dependencies:
  ffi: ^0.1.3
