name: gl_dart
version: 0.0.1-dev.3
author: Vinogadov Alexander <armacoty@protonmail.com>
description: dart:ffi bindings for OpenGL

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: any
dependencies:
  ffi: any