name: gl_dart
version: 0.0.1-beta.1
author: Vinogadov Alexander <armacoty@protonmail.com>
description: dart:ffi bindings for OpenGL

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.12.0
dependencies:
  ffi: ^0.1.3