import 'gl_typedefs.dart';
import 'dart:ffi';

class Gl {
  Gl() {
    String path = "/usr/lib/x86_64-linux-gnu/libGL.so";
    final dylib = DynamicLibrary.open(path);

    this.clearIndex = dylib.lookup<NativeFunction<TglClearIndex_Native>>('glClearIndex').asFunction();
    this.clearColor = dylib.lookup<NativeFunction<TglClearColor_Native>>('glClearColor').asFunction();
    this.clear = dylib.lookup<NativeFunction<TglClear_Native>>('glClear').asFunction();
    this.indexMask = dylib.lookup<NativeFunction<TglIndexMask_Native>>('glIndexMask').asFunction();
    this.colorMask = dylib.lookup<NativeFunction<TglColorMask_Native>>('glColorMask').asFunction();
    this.alphaFunc = dylib.lookup<NativeFunction<TglAlphaFunc_Native>>('glAlphaFunc').asFunction();
    this.blendFunc = dylib.lookup<NativeFunction<TglBlendFunc_Native>>('glBlendFunc').asFunction();
    this.logicOp = dylib.lookup<NativeFunction<TglLogicOp_Native>>('glLogicOp').asFunction();
    this.cullFace = dylib.lookup<NativeFunction<TglCullFace_Native>>('glCullFace').asFunction();
    this.frontFace = dylib.lookup<NativeFunction<TglFrontFace_Native>>('glFrontFace').asFunction();
    this.pointSize = dylib.lookup<NativeFunction<TglPointSize_Native>>('glPointSize').asFunction();
    this.lineWidth = dylib.lookup<NativeFunction<TglLineWidth_Native>>('glLineWidth').asFunction();
    this.lineStipple = dylib.lookup<NativeFunction<TglLineStipple_Native>>('glLineStipple').asFunction();
    this.polygonMode = dylib.lookup<NativeFunction<TglPolygonMode_Native>>('glPolygonMode').asFunction();
    this.polygonOffset = dylib.lookup<NativeFunction<TglPolygonOffset_Native>>('glPolygonOffset').asFunction();
    this.polygonStipple = dylib.lookup<NativeFunction<TglPolygonStipple_Native>>('glPolygonStipple').asFunction();
    this.getPolygonStipple = dylib.lookup<NativeFunction<TglGetPolygonStipple_Native>>('glGetPolygonStipple').asFunction();
    this.edgeFlag = dylib.lookup<NativeFunction<TglEdgeFlag_Native>>('glEdgeFlag').asFunction();
    this.edgeFlagv = dylib.lookup<NativeFunction<TglEdgeFlagv_Native>>('glEdgeFlagv').asFunction();
    this.scissor = dylib.lookup<NativeFunction<TglScissor_Native>>('glScissor').asFunction();
    this.clipPlane = dylib.lookup<NativeFunction<TglClipPlane_Native>>('glClipPlane').asFunction();
    this.getClipPlane = dylib.lookup<NativeFunction<TglGetClipPlane_Native>>('glGetClipPlane').asFunction();
    this.drawBuffer = dylib.lookup<NativeFunction<TglDrawBuffer_Native>>('glDrawBuffer').asFunction();
    this.readBuffer = dylib.lookup<NativeFunction<TglReadBuffer_Native>>('glReadBuffer').asFunction();
    this.enable = dylib.lookup<NativeFunction<TglEnable_Native>>('glEnable').asFunction();
    this.disable = dylib.lookup<NativeFunction<TglDisable_Native>>('glDisable').asFunction();
    this.isEnabled = dylib.lookup<NativeFunction<TglIsEnabled_Native>>('glIsEnabled').asFunction();
    this.enableClientState = dylib.lookup<NativeFunction<TglEnableClientState_Native>>('glEnableClientState').asFunction();
    this.disableClientState = dylib.lookup<NativeFunction<TglDisableClientState_Native>>('glDisableClientState').asFunction();
    this.getBooleanv = dylib.lookup<NativeFunction<TglGetBooleanv_Native>>('glGetBooleanv').asFunction();
    this.getDoublev = dylib.lookup<NativeFunction<TglGetDoublev_Native>>('glGetDoublev').asFunction();
    this.getFloatv = dylib.lookup<NativeFunction<TglGetFloatv_Native>>('glGetFloatv').asFunction();
    this.getIntegerv = dylib.lookup<NativeFunction<TglGetIntegerv_Native>>('glGetIntegerv').asFunction();
    this.pushAttrib = dylib.lookup<NativeFunction<TglPushAttrib_Native>>('glPushAttrib').asFunction();
    this.popAttrib = dylib.lookup<NativeFunction<TglPopAttrib_Native>>('glPopAttrib').asFunction();
    this.pushClientAttrib = dylib.lookup<NativeFunction<TglPushClientAttrib_Native>>('glPushClientAttrib').asFunction();
    this.popClientAttrib = dylib.lookup<NativeFunction<TglPopClientAttrib_Native>>('glPopClientAttrib').asFunction();
    this.renderMode = dylib.lookup<NativeFunction<TglRenderMode_Native>>('glRenderMode').asFunction();
    this.getError = dylib.lookup<NativeFunction<TglGetError_Native>>('glGetError').asFunction();
    this.getString = dylib.lookup<NativeFunction<TglGetString_Native>>('glGetString').asFunction();
    this.finish = dylib.lookup<NativeFunction<TglFinish_Native>>('glFinish').asFunction();
    this.flush = dylib.lookup<NativeFunction<TglFlush_Native>>('glFlush').asFunction();
    this.hint = dylib.lookup<NativeFunction<TglHint_Native>>('glHint').asFunction();
    this.clearDepth = dylib.lookup<NativeFunction<TglClearDepth_Native>>('glClearDepth').asFunction();
    this.depthFunc = dylib.lookup<NativeFunction<TglDepthFunc_Native>>('glDepthFunc').asFunction();
    this.depthMask = dylib.lookup<NativeFunction<TglDepthMask_Native>>('glDepthMask').asFunction();
    this.depthRange = dylib.lookup<NativeFunction<TglDepthRange_Native>>('glDepthRange').asFunction();
    this.clearAccum = dylib.lookup<NativeFunction<TglClearAccum_Native>>('glClearAccum').asFunction();
    this.accum = dylib.lookup<NativeFunction<TglAccum_Native>>('glAccum').asFunction();
    this.matrixMode = dylib.lookup<NativeFunction<TglMatrixMode_Native>>('glMatrixMode').asFunction();
    this.ortho = dylib.lookup<NativeFunction<TglOrtho_Native>>('glOrtho').asFunction();
    this.frustum = dylib.lookup<NativeFunction<TglFrustum_Native>>('glFrustum').asFunction();
    this.viewport = dylib.lookup<NativeFunction<TglViewport_Native>>('glViewport').asFunction();
    this.pushMatrix = dylib.lookup<NativeFunction<TglPushMatrix_Native>>('glPushMatrix').asFunction();
    this.popMatrix = dylib.lookup<NativeFunction<TglPopMatrix_Native>>('glPopMatrix').asFunction();
    this.loadIdentity = dylib.lookup<NativeFunction<TglLoadIdentity_Native>>('glLoadIdentity').asFunction();
    this.loadMatrixd = dylib.lookup<NativeFunction<TglLoadMatrixd_Native>>('glLoadMatrixd').asFunction();
    this.loadMatrixf = dylib.lookup<NativeFunction<TglLoadMatrixf_Native>>('glLoadMatrixf').asFunction();
    this.multMatrixd = dylib.lookup<NativeFunction<TglMultMatrixd_Native>>('glMultMatrixd').asFunction();
    this.multMatrixf = dylib.lookup<NativeFunction<TglMultMatrixf_Native>>('glMultMatrixf').asFunction();
    this.rotated = dylib.lookup<NativeFunction<TglRotated_Native>>('glRotated').asFunction();
    this.rotatef = dylib.lookup<NativeFunction<TglRotatef_Native>>('glRotatef').asFunction();
    this.scaled = dylib.lookup<NativeFunction<TglScaled_Native>>('glScaled').asFunction();
    this.scalef = dylib.lookup<NativeFunction<TglScalef_Native>>('glScalef').asFunction();
    this.translated = dylib.lookup<NativeFunction<TglTranslated_Native>>('glTranslated').asFunction();
    this.translatef = dylib.lookup<NativeFunction<TglTranslatef_Native>>('glTranslatef').asFunction();
    this.isList = dylib.lookup<NativeFunction<TglIsList_Native>>('glIsList').asFunction();
    this.deleteLists = dylib.lookup<NativeFunction<TglDeleteLists_Native>>('glDeleteLists').asFunction();
    this.genLists = dylib.lookup<NativeFunction<TglGenLists_Native>>('glGenLists').asFunction();
    this.newList = dylib.lookup<NativeFunction<TglNewList_Native>>('glNewList').asFunction();
    this.endList = dylib.lookup<NativeFunction<TglEndList_Native>>('glEndList').asFunction();
    this.callList = dylib.lookup<NativeFunction<TglCallList_Native>>('glCallList').asFunction();
    this.callLists = dylib.lookup<NativeFunction<TglCallLists_Native>>('glCallLists').asFunction();
    this.listBase = dylib.lookup<NativeFunction<TglListBase_Native>>('glListBase').asFunction();
    this.begin = dylib.lookup<NativeFunction<TglBegin_Native>>('glBegin').asFunction();
    this.end = dylib.lookup<NativeFunction<TglEnd_Native>>('glEnd').asFunction();
    this.vertex2d = dylib.lookup<NativeFunction<TglVertex2d_Native>>('glVertex2d').asFunction();
    this.vertex2f = dylib.lookup<NativeFunction<TglVertex2f_Native>>('glVertex2f').asFunction();
    this.vertex2i = dylib.lookup<NativeFunction<TglVertex2i_Native>>('glVertex2i').asFunction();
    this.vertex2s = dylib.lookup<NativeFunction<TglVertex2s_Native>>('glVertex2s').asFunction();
    this.vertex3d = dylib.lookup<NativeFunction<TglVertex3d_Native>>('glVertex3d').asFunction();
    this.vertex3f = dylib.lookup<NativeFunction<TglVertex3f_Native>>('glVertex3f').asFunction();
    this.vertex3i = dylib.lookup<NativeFunction<TglVertex3i_Native>>('glVertex3i').asFunction();
    this.vertex3s = dylib.lookup<NativeFunction<TglVertex3s_Native>>('glVertex3s').asFunction();
    this.vertex4d = dylib.lookup<NativeFunction<TglVertex4d_Native>>('glVertex4d').asFunction();
    this.vertex4f = dylib.lookup<NativeFunction<TglVertex4f_Native>>('glVertex4f').asFunction();
    this.vertex4i = dylib.lookup<NativeFunction<TglVertex4i_Native>>('glVertex4i').asFunction();
    this.vertex4s = dylib.lookup<NativeFunction<TglVertex4s_Native>>('glVertex4s').asFunction();
    this.vertex2dv = dylib.lookup<NativeFunction<TglVertex2dv_Native>>('glVertex2dv').asFunction();
    this.vertex2fv = dylib.lookup<NativeFunction<TglVertex2fv_Native>>('glVertex2fv').asFunction();
    this.vertex2iv = dylib.lookup<NativeFunction<TglVertex2iv_Native>>('glVertex2iv').asFunction();
    this.vertex2sv = dylib.lookup<NativeFunction<TglVertex2sv_Native>>('glVertex2sv').asFunction();
    this.vertex3dv = dylib.lookup<NativeFunction<TglVertex3dv_Native>>('glVertex3dv').asFunction();
    this.vertex3fv = dylib.lookup<NativeFunction<TglVertex3fv_Native>>('glVertex3fv').asFunction();
    this.vertex3iv = dylib.lookup<NativeFunction<TglVertex3iv_Native>>('glVertex3iv').asFunction();
    this.vertex3sv = dylib.lookup<NativeFunction<TglVertex3sv_Native>>('glVertex3sv').asFunction();
    this.vertex4dv = dylib.lookup<NativeFunction<TglVertex4dv_Native>>('glVertex4dv').asFunction();
    this.vertex4fv = dylib.lookup<NativeFunction<TglVertex4fv_Native>>('glVertex4fv').asFunction();
    this.vertex4iv = dylib.lookup<NativeFunction<TglVertex4iv_Native>>('glVertex4iv').asFunction();
    this.vertex4sv = dylib.lookup<NativeFunction<TglVertex4sv_Native>>('glVertex4sv').asFunction();
    this.normal3b = dylib.lookup<NativeFunction<TglNormal3b_Native>>('glNormal3b').asFunction();
    this.normal3d = dylib.lookup<NativeFunction<TglNormal3d_Native>>('glNormal3d').asFunction();
    this.normal3f = dylib.lookup<NativeFunction<TglNormal3f_Native>>('glNormal3f').asFunction();
    this.normal3i = dylib.lookup<NativeFunction<TglNormal3i_Native>>('glNormal3i').asFunction();
    this.normal3s = dylib.lookup<NativeFunction<TglNormal3s_Native>>('glNormal3s').asFunction();
    this.normal3bv = dylib.lookup<NativeFunction<TglNormal3bv_Native>>('glNormal3bv').asFunction();
    this.normal3dv = dylib.lookup<NativeFunction<TglNormal3dv_Native>>('glNormal3dv').asFunction();
    this.normal3fv = dylib.lookup<NativeFunction<TglNormal3fv_Native>>('glNormal3fv').asFunction();
    this.normal3iv = dylib.lookup<NativeFunction<TglNormal3iv_Native>>('glNormal3iv').asFunction();
    this.normal3sv = dylib.lookup<NativeFunction<TglNormal3sv_Native>>('glNormal3sv').asFunction();
    this.indexd = dylib.lookup<NativeFunction<TglIndexd_Native>>('glIndexd').asFunction();
    this.indexf = dylib.lookup<NativeFunction<TglIndexf_Native>>('glIndexf').asFunction();
    this.indexi = dylib.lookup<NativeFunction<TglIndexi_Native>>('glIndexi').asFunction();
    this.indexs = dylib.lookup<NativeFunction<TglIndexs_Native>>('glIndexs').asFunction();
    this.indexub = dylib.lookup<NativeFunction<TglIndexub_Native>>('glIndexub').asFunction();
    this.indexdv = dylib.lookup<NativeFunction<TglIndexdv_Native>>('glIndexdv').asFunction();
    this.indexfv = dylib.lookup<NativeFunction<TglIndexfv_Native>>('glIndexfv').asFunction();
    this.indexiv = dylib.lookup<NativeFunction<TglIndexiv_Native>>('glIndexiv').asFunction();
    this.indexsv = dylib.lookup<NativeFunction<TglIndexsv_Native>>('glIndexsv').asFunction();
    this.indexubv = dylib.lookup<NativeFunction<TglIndexubv_Native>>('glIndexubv').asFunction();
    this.color3b = dylib.lookup<NativeFunction<TglColor3b_Native>>('glColor3b').asFunction();
    this.color3d = dylib.lookup<NativeFunction<TglColor3d_Native>>('glColor3d').asFunction();
    this.color3f = dylib.lookup<NativeFunction<TglColor3f_Native>>('glColor3f').asFunction();
    this.color3i = dylib.lookup<NativeFunction<TglColor3i_Native>>('glColor3i').asFunction();
    this.color3s = dylib.lookup<NativeFunction<TglColor3s_Native>>('glColor3s').asFunction();
    this.color3ub = dylib.lookup<NativeFunction<TglColor3ub_Native>>('glColor3ub').asFunction();
    this.color3ui = dylib.lookup<NativeFunction<TglColor3ui_Native>>('glColor3ui').asFunction();
    this.color3us = dylib.lookup<NativeFunction<TglColor3us_Native>>('glColor3us').asFunction();
    this.color4b = dylib.lookup<NativeFunction<TglColor4b_Native>>('glColor4b').asFunction();
    this.color4d = dylib.lookup<NativeFunction<TglColor4d_Native>>('glColor4d').asFunction();
    this.color4f = dylib.lookup<NativeFunction<TglColor4f_Native>>('glColor4f').asFunction();
    this.color4i = dylib.lookup<NativeFunction<TglColor4i_Native>>('glColor4i').asFunction();
    this.color4s = dylib.lookup<NativeFunction<TglColor4s_Native>>('glColor4s').asFunction();
    this.color4ub = dylib.lookup<NativeFunction<TglColor4ub_Native>>('glColor4ub').asFunction();
    this.color4ui = dylib.lookup<NativeFunction<TglColor4ui_Native>>('glColor4ui').asFunction();
    this.color4us = dylib.lookup<NativeFunction<TglColor4us_Native>>('glColor4us').asFunction();
    this.color3bv = dylib.lookup<NativeFunction<TglColor3bv_Native>>('glColor3bv').asFunction();
    this.color3dv = dylib.lookup<NativeFunction<TglColor3dv_Native>>('glColor3dv').asFunction();
    this.color3fv = dylib.lookup<NativeFunction<TglColor3fv_Native>>('glColor3fv').asFunction();
    this.color3iv = dylib.lookup<NativeFunction<TglColor3iv_Native>>('glColor3iv').asFunction();
    this.color3sv = dylib.lookup<NativeFunction<TglColor3sv_Native>>('glColor3sv').asFunction();
    this.color3ubv = dylib.lookup<NativeFunction<TglColor3ubv_Native>>('glColor3ubv').asFunction();
    this.color3uiv = dylib.lookup<NativeFunction<TglColor3uiv_Native>>('glColor3uiv').asFunction();
    this.color3usv = dylib.lookup<NativeFunction<TglColor3usv_Native>>('glColor3usv').asFunction();
    this.color4bv = dylib.lookup<NativeFunction<TglColor4bv_Native>>('glColor4bv').asFunction();
    this.color4dv = dylib.lookup<NativeFunction<TglColor4dv_Native>>('glColor4dv').asFunction();
    this.color4fv = dylib.lookup<NativeFunction<TglColor4fv_Native>>('glColor4fv').asFunction();
    this.color4iv = dylib.lookup<NativeFunction<TglColor4iv_Native>>('glColor4iv').asFunction();
    this.color4sv = dylib.lookup<NativeFunction<TglColor4sv_Native>>('glColor4sv').asFunction();
    this.color4ubv = dylib.lookup<NativeFunction<TglColor4ubv_Native>>('glColor4ubv').asFunction();
    this.color4uiv = dylib.lookup<NativeFunction<TglColor4uiv_Native>>('glColor4uiv').asFunction();
    this.color4usv = dylib.lookup<NativeFunction<TglColor4usv_Native>>('glColor4usv').asFunction();
    this.texCoord1d = dylib.lookup<NativeFunction<TglTexCoord1d_Native>>('glTexCoord1d').asFunction();
    this.texCoord1f = dylib.lookup<NativeFunction<TglTexCoord1f_Native>>('glTexCoord1f').asFunction();
    this.texCoord1i = dylib.lookup<NativeFunction<TglTexCoord1i_Native>>('glTexCoord1i').asFunction();
    this.texCoord1s = dylib.lookup<NativeFunction<TglTexCoord1s_Native>>('glTexCoord1s').asFunction();
    this.texCoord2d = dylib.lookup<NativeFunction<TglTexCoord2d_Native>>('glTexCoord2d').asFunction();
    this.texCoord2f = dylib.lookup<NativeFunction<TglTexCoord2f_Native>>('glTexCoord2f').asFunction();
    this.texCoord2i = dylib.lookup<NativeFunction<TglTexCoord2i_Native>>('glTexCoord2i').asFunction();
    this.texCoord2s = dylib.lookup<NativeFunction<TglTexCoord2s_Native>>('glTexCoord2s').asFunction();
    this.texCoord3d = dylib.lookup<NativeFunction<TglTexCoord3d_Native>>('glTexCoord3d').asFunction();
    this.texCoord3f = dylib.lookup<NativeFunction<TglTexCoord3f_Native>>('glTexCoord3f').asFunction();
    this.texCoord3i = dylib.lookup<NativeFunction<TglTexCoord3i_Native>>('glTexCoord3i').asFunction();
    this.texCoord3s = dylib.lookup<NativeFunction<TglTexCoord3s_Native>>('glTexCoord3s').asFunction();
    this.texCoord4d = dylib.lookup<NativeFunction<TglTexCoord4d_Native>>('glTexCoord4d').asFunction();
    this.texCoord4f = dylib.lookup<NativeFunction<TglTexCoord4f_Native>>('glTexCoord4f').asFunction();
    this.texCoord4i = dylib.lookup<NativeFunction<TglTexCoord4i_Native>>('glTexCoord4i').asFunction();
    this.texCoord4s = dylib.lookup<NativeFunction<TglTexCoord4s_Native>>('glTexCoord4s').asFunction();
    this.texCoord1dv = dylib.lookup<NativeFunction<TglTexCoord1dv_Native>>('glTexCoord1dv').asFunction();
    this.texCoord1fv = dylib.lookup<NativeFunction<TglTexCoord1fv_Native>>('glTexCoord1fv').asFunction();
    this.texCoord1iv = dylib.lookup<NativeFunction<TglTexCoord1iv_Native>>('glTexCoord1iv').asFunction();
    this.texCoord1sv = dylib.lookup<NativeFunction<TglTexCoord1sv_Native>>('glTexCoord1sv').asFunction();
    this.texCoord2dv = dylib.lookup<NativeFunction<TglTexCoord2dv_Native>>('glTexCoord2dv').asFunction();
    this.texCoord2fv = dylib.lookup<NativeFunction<TglTexCoord2fv_Native>>('glTexCoord2fv').asFunction();
    this.texCoord2iv = dylib.lookup<NativeFunction<TglTexCoord2iv_Native>>('glTexCoord2iv').asFunction();
    this.texCoord2sv = dylib.lookup<NativeFunction<TglTexCoord2sv_Native>>('glTexCoord2sv').asFunction();
    this.texCoord3dv = dylib.lookup<NativeFunction<TglTexCoord3dv_Native>>('glTexCoord3dv').asFunction();
    this.texCoord3fv = dylib.lookup<NativeFunction<TglTexCoord3fv_Native>>('glTexCoord3fv').asFunction();
    this.texCoord3iv = dylib.lookup<NativeFunction<TglTexCoord3iv_Native>>('glTexCoord3iv').asFunction();
    this.texCoord3sv = dylib.lookup<NativeFunction<TglTexCoord3sv_Native>>('glTexCoord3sv').asFunction();
    this.texCoord4dv = dylib.lookup<NativeFunction<TglTexCoord4dv_Native>>('glTexCoord4dv').asFunction();
    this.texCoord4fv = dylib.lookup<NativeFunction<TglTexCoord4fv_Native>>('glTexCoord4fv').asFunction();
    this.texCoord4iv = dylib.lookup<NativeFunction<TglTexCoord4iv_Native>>('glTexCoord4iv').asFunction();
    this.texCoord4sv = dylib.lookup<NativeFunction<TglTexCoord4sv_Native>>('glTexCoord4sv').asFunction();
    this.rasterPos2d = dylib.lookup<NativeFunction<TglRasterPos2d_Native>>('glRasterPos2d').asFunction();
    this.rasterPos2f = dylib.lookup<NativeFunction<TglRasterPos2f_Native>>('glRasterPos2f').asFunction();
    this.rasterPos2i = dylib.lookup<NativeFunction<TglRasterPos2i_Native>>('glRasterPos2i').asFunction();
    this.rasterPos2s = dylib.lookup<NativeFunction<TglRasterPos2s_Native>>('glRasterPos2s').asFunction();
    this.rasterPos3d = dylib.lookup<NativeFunction<TglRasterPos3d_Native>>('glRasterPos3d').asFunction();
    this.rasterPos3f = dylib.lookup<NativeFunction<TglRasterPos3f_Native>>('glRasterPos3f').asFunction();
    this.rasterPos3i = dylib.lookup<NativeFunction<TglRasterPos3i_Native>>('glRasterPos3i').asFunction();
    this.rasterPos3s = dylib.lookup<NativeFunction<TglRasterPos3s_Native>>('glRasterPos3s').asFunction();
    this.rasterPos4d = dylib.lookup<NativeFunction<TglRasterPos4d_Native>>('glRasterPos4d').asFunction();
    this.rasterPos4f = dylib.lookup<NativeFunction<TglRasterPos4f_Native>>('glRasterPos4f').asFunction();
    this.rasterPos4i = dylib.lookup<NativeFunction<TglRasterPos4i_Native>>('glRasterPos4i').asFunction();
    this.rasterPos4s = dylib.lookup<NativeFunction<TglRasterPos4s_Native>>('glRasterPos4s').asFunction();
    this.rasterPos2dv = dylib.lookup<NativeFunction<TglRasterPos2dv_Native>>('glRasterPos2dv').asFunction();
    this.rasterPos2fv = dylib.lookup<NativeFunction<TglRasterPos2fv_Native>>('glRasterPos2fv').asFunction();
    this.rasterPos2iv = dylib.lookup<NativeFunction<TglRasterPos2iv_Native>>('glRasterPos2iv').asFunction();
    this.rasterPos2sv = dylib.lookup<NativeFunction<TglRasterPos2sv_Native>>('glRasterPos2sv').asFunction();
    this.rasterPos3dv = dylib.lookup<NativeFunction<TglRasterPos3dv_Native>>('glRasterPos3dv').asFunction();
    this.rasterPos3fv = dylib.lookup<NativeFunction<TglRasterPos3fv_Native>>('glRasterPos3fv').asFunction();
    this.rasterPos3iv = dylib.lookup<NativeFunction<TglRasterPos3iv_Native>>('glRasterPos3iv').asFunction();
    this.rasterPos3sv = dylib.lookup<NativeFunction<TglRasterPos3sv_Native>>('glRasterPos3sv').asFunction();
    this.rasterPos4dv = dylib.lookup<NativeFunction<TglRasterPos4dv_Native>>('glRasterPos4dv').asFunction();
    this.rasterPos4fv = dylib.lookup<NativeFunction<TglRasterPos4fv_Native>>('glRasterPos4fv').asFunction();
    this.rasterPos4iv = dylib.lookup<NativeFunction<TglRasterPos4iv_Native>>('glRasterPos4iv').asFunction();
    this.rasterPos4sv = dylib.lookup<NativeFunction<TglRasterPos4sv_Native>>('glRasterPos4sv').asFunction();
    this.rectd = dylib.lookup<NativeFunction<TglRectd_Native>>('glRectd').asFunction();
    this.rectf = dylib.lookup<NativeFunction<TglRectf_Native>>('glRectf').asFunction();
    this.recti = dylib.lookup<NativeFunction<TglRecti_Native>>('glRecti').asFunction();
    this.rects = dylib.lookup<NativeFunction<TglRects_Native>>('glRects').asFunction();
    this.rectdv = dylib.lookup<NativeFunction<TglRectdv_Native>>('glRectdv').asFunction();
    this.rectfv = dylib.lookup<NativeFunction<TglRectfv_Native>>('glRectfv').asFunction();
    this.rectiv = dylib.lookup<NativeFunction<TglRectiv_Native>>('glRectiv').asFunction();
    this.rectsv = dylib.lookup<NativeFunction<TglRectsv_Native>>('glRectsv').asFunction();
    this.vertexPointer = dylib.lookup<NativeFunction<TglVertexPointer_Native>>('glVertexPointer').asFunction();
    this.normalPointer = dylib.lookup<NativeFunction<TglNormalPointer_Native>>('glNormalPointer').asFunction();
    this.colorPointer = dylib.lookup<NativeFunction<TglColorPointer_Native>>('glColorPointer').asFunction();
    this.indexPointer = dylib.lookup<NativeFunction<TglIndexPointer_Native>>('glIndexPointer').asFunction();
    this.texCoordPointer = dylib.lookup<NativeFunction<TglTexCoordPointer_Native>>('glTexCoordPointer').asFunction();
    this.edgeFlagPointer = dylib.lookup<NativeFunction<TglEdgeFlagPointer_Native>>('glEdgeFlagPointer').asFunction();
    this.getPointerv = dylib.lookup<NativeFunction<TglGetPointerv_Native>>('glGetPointerv').asFunction();
    this.arrayElement = dylib.lookup<NativeFunction<TglArrayElement_Native>>('glArrayElement').asFunction();
    this.drawArrays = dylib.lookup<NativeFunction<TglDrawArrays_Native>>('glDrawArrays').asFunction();
    this.drawElements = dylib.lookup<NativeFunction<TglDrawElements_Native>>('glDrawElements').asFunction();
    this.interleavedArrays = dylib.lookup<NativeFunction<TglInterleavedArrays_Native>>('interleavedArrays').asFunction();
    this.shadeModel = dylib.lookup<NativeFunction<TglShadeModel_Native>>('glShadeModel').asFunction();
    this.lightf = dylib.lookup<NativeFunction<TglLightf_Native>>('glLightf').asFunction();
    this.lighti = dylib.lookup<NativeFunction<TglLighti_Native>>('glLighti').asFunction();
    this.lightfv = dylib.lookup<NativeFunction<TglLightfv_Native>>('glLightfv').asFunction();
    this.lightiv = dylib.lookup<NativeFunction<TglLightiv_Native>>('glLightiv').asFunction();
    this.getLightfv = dylib.lookup<NativeFunction<TglGetLightfv_Native>>('glGetLightfv').asFunction();
    this.getLightiv = dylib.lookup<NativeFunction<TglGetLightiv_Native>>('glGetLightiv').asFunction();
    this.lightModelf = dylib.lookup<NativeFunction<TglLightModelf_Native>>('glLightModelf').asFunction();
    this.lightModeli = dylib.lookup<NativeFunction<TglLightModeli_Native>>('glLightModeli').asFunction();
    this.lightModelfv = dylib.lookup<NativeFunction<TglLightModelfv_Native>>('glLightModelfv').asFunction();
    this.lightModeliv = dylib.lookup<NativeFunction<TglLightModeliv_Native>>('glLightModeliv').asFunction();
    this.materialf = dylib.lookup<NativeFunction<TglMaterialf_Native>>('glMaterialf').asFunction();
    this.materiali = dylib.lookup<NativeFunction<TglMateriali_Native>>('glMateriali').asFunction();
    this.materialfv = dylib.lookup<NativeFunction<TglMaterialfv_Native>>('glMaterialfv').asFunction();
    this.materialiv = dylib.lookup<NativeFunction<TglMaterialiv_Native>>('glMaterialiv').asFunction();
    this.getMaterialfv = dylib.lookup<NativeFunction<TglGetMaterialfv_Native>>('glGetMaterialfv').asFunction();
    this.getMaterialiv = dylib.lookup<NativeFunction<TglGetMaterialiv_Native>>('glGetMaterialiv').asFunction();
    this.colorMaterial = dylib.lookup<NativeFunction<TglColorMaterial_Native>>('glColorMaterial').asFunction();
    this.pixelZoom = dylib.lookup<NativeFunction<TglPixelZoom_Native>>('glPixelZoom').asFunction();
    this.pixelStoref = dylib.lookup<NativeFunction<TglPixelStoref_Native>>('glPixelStoref').asFunction();
    this.pixelStorei = dylib.lookup<NativeFunction<TglPixelStorei_Native>>('glPixelStorei').asFunction();
    this.pixelTransferf = dylib.lookup<NativeFunction<TglPixelTransferf_Native>>('glPixelTransferf').asFunction();
    this.pixelTransferi = dylib.lookup<NativeFunction<TglPixelTransferi_Native>>('glPixelTransferi').asFunction();
    this.pixelMapfv = dylib.lookup<NativeFunction<TglPixelMapfv_Native>>('glPixelMapfv').asFunction();
    this.pixelMapuiv = dylib.lookup<NativeFunction<TglPixelMapuiv_Native>>('glPixelMapuiv').asFunction();
    this.pixelMapusv = dylib.lookup<NativeFunction<TglPixelMapusv_Native>>('glPixelMapusv').asFunction();
    this.getPixelMapfv = dylib.lookup<NativeFunction<TglGetPixelMapfv_Native>>('glGetPixelMapfv').asFunction();
    this.getPixelMapuiv = dylib.lookup<NativeFunction<TglGetPixelMapuiv_Native>>('glGetPixelMapuiv').asFunction();
    this.getPixelMapusv = dylib.lookup<NativeFunction<TglGetPixelMapusv_Native>>('glGetPixelMapusv').asFunction();
    this.bitmap = dylib.lookup<NativeFunction<TglBitmap_Native>>('glBitmap').asFunction();
    this.readPixels = dylib.lookup<NativeFunction<TglReadPixels_Native>>('glReadPixels').asFunction();
    this.drawPixels = dylib.lookup<NativeFunction<TglDrawPixels_Native>>('glDrawPixels').asFunction();
    this.copyPixels = dylib.lookup<NativeFunction<TglCopyPixels_Native>>('glCopyPixels').asFunction();
    this.stencilFunc = dylib.lookup<NativeFunction<TglStencilFunc_Native>>('glStencilFunc').asFunction();
    this.stencilMask = dylib.lookup<NativeFunction<TglStencilMask_Native>>('glStencilMask').asFunction();
    this.stencilOp = dylib.lookup<NativeFunction<TglStencilOp_Native>>('glStencilOp').asFunction();
    this.clearStencil = dylib.lookup<NativeFunction<TglClearStencil_Native>>('glClearStencil').asFunction();
    this.texGend = dylib.lookup<NativeFunction<TglTexGend_Native>>('glTexGend').asFunction();
    this.texGenf = dylib.lookup<NativeFunction<TglTexGenf_Native>>('glTexGenf').asFunction();
    this.texGeni = dylib.lookup<NativeFunction<TglTexGeni_Native>>('glTexGeni').asFunction();
    this.texGendv = dylib.lookup<NativeFunction<TglTexGendv_Native>>('glTexGendv').asFunction();
    this.texGenfv = dylib.lookup<NativeFunction<TglTexGenfv_Native>>('glTexGenfv').asFunction();
    this.texGeniv = dylib.lookup<NativeFunction<TglTexGeniv_Native>>('glTexGeniv').asFunction();
    this.getTexGendv = dylib.lookup<NativeFunction<TglGetTexGendv_Native>>('glGetTexGendv').asFunction();
    this.getTexGenfv = dylib.lookup<NativeFunction<TglGetTexGenfv_Native>>('glGetTexGenfv').asFunction();
    this.getTexGeniv = dylib.lookup<NativeFunction<TglGetTexGeniv_Native>>('glGetTexGeniv').asFunction();
    this.texEnvf = dylib.lookup<NativeFunction<TglTexEnvf_Native>>('glTexEnvf').asFunction();
    this.texEnvi = dylib.lookup<NativeFunction<TglTexEnvi_Native>>('glTexEnvi').asFunction();
    this.texEnvfv = dylib.lookup<NativeFunction<TglTexEnvfv_Native>>('glTexEnvfv').asFunction();
    this.texEnviv = dylib.lookup<NativeFunction<TglTexEnviv_Native>>('glTexEnviv').asFunction();
    this.getTexEnvfv = dylib.lookup<NativeFunction<TglGetTexEnvfv_Native>>('glGetTexEnvfv').asFunction();
    this.getTexEnviv = dylib.lookup<NativeFunction<TglGetTexEnviv_Native>>('glGetTexEnviv').asFunction();
    this.texParameterf = dylib.lookup<NativeFunction<TglTexParameterf_Native>>('glTexParameterf').asFunction();
    this.texParameteri = dylib.lookup<NativeFunction<TglTexParameteri_Native>>('glTexParameteri').asFunction();
    this.texParameterfv = dylib.lookup<NativeFunction<TglTexParameterfv_Native>>('glTexParameterfv').asFunction();
    this.texParameteriv = dylib.lookup<NativeFunction<TglTexParameteriv_Native>>('glTexParameteriv').asFunction();
    this.getTexParameterfv = dylib.lookup<NativeFunction<TglGetTexParameterfv_Native>>('glGetTexParameterfv').asFunction();
    this.getTexParameteriv = dylib.lookup<NativeFunction<TglGetTexParameteriv_Native>>('glGetTexParameteriv').asFunction();
    this.getTexLevelParameterfv = dylib.lookup<NativeFunction<TglGetTexLevelParameterfv_Native>>('glGetTexLevelParameterfv').asFunction();
    this.getTexLevelParameteriv = dylib.lookup<NativeFunction<TglGetTexLevelParameteriv_Native>>('glGetTexLevelParameteriv').asFunction();
    this.texImage1D = dylib.lookup<NativeFunction<TglTexImage1D_Native>>('glTexImage1D').asFunction();
    this.texImage2D = dylib.lookup<NativeFunction<TglTexImage2D_Native>>('glTexImage2D').asFunction();
    this.getTexImage = dylib.lookup<NativeFunction<TglGetTexImage_Native>>('glGetTexImage').asFunction();
    this.genTextures = dylib.lookup<NativeFunction<TglGenTextures_Native>>('glGenTextures').asFunction();
    this.deleteTextures = dylib.lookup<NativeFunction<TglDeleteTextures_Native>>('glDeleteTextures').asFunction();
    this.bindTexture = dylib.lookup<NativeFunction<TglBindTexture_Native>>('glBindTexture').asFunction();
    this.prioritizeTextures = dylib.lookup<NativeFunction<TglPrioritizeTextures_Native>>('glPrioritizeTextures').asFunction();
    this.areTexturesResident = dylib.lookup<NativeFunction<TglAreTexturesResident_Native>>('glAreTexturesResident').asFunction();
    this.isTexture = dylib.lookup<NativeFunction<TglIsTexture_Native>>('glIsTexture').asFunction();
    this.texSubImage1D = dylib.lookup<NativeFunction<TglTexSubImage1D_Native>>('glTexSubImage1D').asFunction();
    this.texSubImage2D = dylib.lookup<NativeFunction<TglTexSubImage2D_Native>>('glTexSubImage2D').asFunction();
    this.copyTexImage1D = dylib.lookup<NativeFunction<TglCopyTexImage1D_Native>>('glCopyTexImage1D').asFunction();
    this.copyTexImage2D = dylib.lookup<NativeFunction<TglCopyTexImage2D_Native>>('glCopyTexImage2D').asFunction();
    this.copyTexSubImage1D = dylib.lookup<NativeFunction<TglCopyTexSubImage1D_Native>>('glCopyTexSubImage1D').asFunction();
    this.copyTexSubImage2D = dylib.lookup<NativeFunction<TglCopyTexSubImage2D_Native>>('glCopyTexSubImage2D').asFunction();
    this.map1d = dylib.lookup<NativeFunction<TglMap1d_Native>>('glMap1d').asFunction();
    this.map1f = dylib.lookup<NativeFunction<TglMap1f_Native>>('glMap1f').asFunction();
    this.map2d = dylib.lookup<NativeFunction<TglMap2d_Native>>('glMap2d').asFunction();
    this.map2f = dylib.lookup<NativeFunction<TglMap2f_Native>>('glMap2f').asFunction();
    this.getMapdv = dylib.lookup<NativeFunction<TglGetMapdv_Native>>('glGetMapdv').asFunction();
    this.getMapfv = dylib.lookup<NativeFunction<TglGetMapfv_Native>>('glGetMapfv').asFunction();
    this.getMapiv = dylib.lookup<NativeFunction<TglGetMapiv_Native>>('glGetMapiv').asFunction();
    this.evalCoord1d = dylib.lookup<NativeFunction<TglEvalCoord1d_Native>>('glEvalCoord1d').asFunction();
    this.evalCoord1f = dylib.lookup<NativeFunction<TglEvalCoord1f_Native>>('glEvalCoord1f').asFunction();
    this.evalCoord1dv = dylib.lookup<NativeFunction<TglEvalCoord1dv_Native>>('glEvalCoord1dv').asFunction();
    this.evalCoord1fv = dylib.lookup<NativeFunction<TglEvalCoord1fv_Native>>('glEvalCoord1fv').asFunction();
    this.evalCoord2d = dylib.lookup<NativeFunction<TglEvalCoord2d_Native>>('glEvalCoord2d').asFunction();
    this.evalCoord2f = dylib.lookup<NativeFunction<TglEvalCoord2f_Native>>('glEvalCoord2f').asFunction();
    this.evalCoord2dv = dylib.lookup<NativeFunction<TglEvalCoord2dv_Native>>('glEvalCoord2dv').asFunction();
    this.evalCoord2fv = dylib.lookup<NativeFunction<TglEvalCoord2fv_Native>>('glEvalCoord2fv').asFunction();
    this.mapGrid1d = dylib.lookup<NativeFunction<TglMapGrid1d_Native>>('glMapGrid1d').asFunction();
    this.mapGrid1f = dylib.lookup<NativeFunction<TglMapGrid1f_Native>>('glMapGrid1f').asFunction();
    this.mapGrid2d = dylib.lookup<NativeFunction<TglMapGrid2d_Native>>('glMapGrid2d').asFunction();
    this.mapGrid2f = dylib.lookup<NativeFunction<TglMapGrid2f_Native>>('glMapGrid2f').asFunction();
    this.evalPoint1 = dylib.lookup<NativeFunction<TglEvalPoint1_Native>>('glEvalPoint1').asFunction();
    this.evalPoint2 = dylib.lookup<NativeFunction<TglEvalPoint2_Native>>('glEvalPoint2').asFunction();
    this.evalMesh1 = dylib.lookup<NativeFunction<TglEvalMesh1_Native>>('glEvalMesh1').asFunction();
    this.evalMesh2 = dylib.lookup<NativeFunction<TglEvalMesh2_Native>>('glEvalMesh2').asFunction();
    this.fogf = dylib.lookup<NativeFunction<TglFogf_Native>>('glFogf').asFunction();
    this.fogi = dylib.lookup<NativeFunction<TglFogi_Native>>('glFogi').asFunction();
    this.fogfv = dylib.lookup<NativeFunction<TglFogfv_Native>>('glFogfv').asFunction();
    this.fogiv = dylib.lookup<NativeFunction<TglFogiv_Native>>('glFogiv').asFunction();
    this.feedbackBuffer = dylib.lookup<NativeFunction<TglFeedbackBuffer_Native>>('glFeedbackBuffer').asFunction();
    this.passThrough = dylib.lookup<NativeFunction<TglPassThrough_Native>>('glPassThrough').asFunction();
    this.selectBuffer = dylib.lookup<NativeFunction<TglSelectBuffer_Native>>('glSelectBuffer').asFunction();
    this.initNames = dylib.lookup<NativeFunction<TglInitNames_Native>>('glInitNames').asFunction();
    this.loadName = dylib.lookup<NativeFunction<TglLoadName_Native>>('glLoadName').asFunction();
    this.pushName = dylib.lookup<NativeFunction<TglPushName_Native>>('glPushName').asFunction();
    this.popName = dylib.lookup<NativeFunction<TglPopName_Native>>('glPopName').asFunction();
    this.drawRangeElements = dylib.lookup<NativeFunction<TglDrawRangeElements_Native>>('glDrawRangeElements').asFunction();
    this.texImage3D = dylib.lookup<NativeFunction<TglTexImage3D_Native>>('glTexImage3D').asFunction();
    this.texSubImage3D = dylib.lookup<NativeFunction<TglTexSubImage3D_Native>>('glTexSubImage3D').asFunction();
    this.copyTexSubImage3D = dylib.lookup<NativeFunction<TglCopyTexSubImage3D_Native>>('glCopyTexSubImage3D').asFunction();
    this.colorTable = dylib.lookup<NativeFunction<TglColorTable_Native>>('glColorTable').asFunction();
    this.colorSubTable = dylib.lookup<NativeFunction<TglColorSubTable_Native>>('glColorSubTable').asFunction();
    this.colorTableParameteriv = dylib.lookup<NativeFunction<TglColorTableParameteriv_Native>>('glColorTableParameteriv').asFunction();
    this.colorTableParameterfv = dylib.lookup<NativeFunction<TglColorTableParameterfv_Native>>('glColorTableParameterfv').asFunction();
    this.copyColorSubTable = dylib.lookup<NativeFunction<TglCopyColorSubTable_Native>>('glCopyColorSubTable').asFunction();
    this.copyColorTable = dylib.lookup<NativeFunction<TglCopyColorTable_Native>>('glCopyColorTable').asFunction();
    this.getColorTable = dylib.lookup<NativeFunction<TglGetColorTable_Native>>('glGetColorTable').asFunction();
    this.getColorTableParameterfv = dylib.lookup<NativeFunction<TglGetColorTableParameterfv_Native>>('glGetColorTableParameterfv').asFunction();
    this.getColorTableParameteriv = dylib.lookup<NativeFunction<TglGetColorTableParameteriv_Native>>('glGetColorTableParameteriv').asFunction();
    this.blendEquation = dylib.lookup<NativeFunction<TglBlendEquation_Native>>('glBlendEquation').asFunction();
    this.blendColor = dylib.lookup<NativeFunction<TglBlendColor_Native>>('glBlendColor').asFunction();
    this.histogram = dylib.lookup<NativeFunction<TglHistogram_Native>>('glHistogram').asFunction();
    this.resetHistogram = dylib.lookup<NativeFunction<TglResetHistogram_Native>>('glResetHistogram').asFunction();
    this.getHistogram = dylib.lookup<NativeFunction<TglGetHistogram_Native>>('glGetHistogram').asFunction();
    this.getHistogramParameterfv = dylib.lookup<NativeFunction<TglGetHistogramParameterfv_Native>>('glGetHistogramParameterfv').asFunction();
    this.getHistogramParameteriv = dylib.lookup<NativeFunction<TglGetHistogramParameteriv_Native>>('glGetHistogramParameteriv').asFunction();
    this.minmax = dylib.lookup<NativeFunction<TglMinmax_Native>>('glMinmax').asFunction();
    this.resetMinmax = dylib.lookup<NativeFunction<TglResetMinmax_Native>>('glResetMinmax').asFunction();
    this.getMinmax = dylib.lookup<NativeFunction<TglGetMinmax_Native>>('glGetMinmax').asFunction();
    this.getMinmaxParameterfv = dylib.lookup<NativeFunction<TglGetMinmaxParameterfv_Native>>('glGetMinmaxParameterfv').asFunction();
    this.getMinmaxParameteriv = dylib.lookup<NativeFunction<TglGetMinmaxParameteriv_Native>>('glGetMinmaxParameteriv').asFunction();
    this.convolutionFilter1D = dylib.lookup<NativeFunction<TglConvolutionFilter1D_Native>>('glConvolutionFilter1D').asFunction();
    this.convolutionFilter2D = dylib.lookup<NativeFunction<TglConvolutionFilter2D_Native>>('glConvolutionFilter2D').asFunction();
    this.convolutionParameterf = dylib.lookup<NativeFunction<TglConvolutionParameterf_Native>>('glConvolutionParameterf').asFunction();
    this.convolutionParameterfv = dylib.lookup<NativeFunction<TglConvolutionParameterfv_Native>>('glConvolutionParameterfv').asFunction();
    this.convolutionParameteri = dylib.lookup<NativeFunction<TglConvolutionParameteri_Native>>('glConvolutionParameteri').asFunction();
    this.convolutionParameteriv = dylib.lookup<NativeFunction<TglConvolutionParameteriv_Native>>('glConvolutionParameteriv').asFunction();
    this.copyConvolutionFilter1D = dylib.lookup<NativeFunction<TglCopyConvolutionFilter1D_Native>>('glCopyConvolutionFilter1D').asFunction();
    this.copyConvolutionFilter2D = dylib.lookup<NativeFunction<TglCopyConvolutionFilter2D_Native>>('glCopyConvolutionFilter2D').asFunction();
    this.getConvolutionFilter = dylib.lookup<NativeFunction<TglGetConvolutionFilter_Native>>('glGetConvolutionFilter').asFunction();
    this.getConvolutionParameterfv = dylib.lookup<NativeFunction<TglGetConvolutionParameterfv_Native>>('glGetConvolutionParameterfv').asFunction();
    this.getConvolutionParameteriv = dylib.lookup<NativeFunction<TglGetConvolutionParameteriv_Native>>('glGetConvolutionParameteriv').asFunction();
    this.separableFilter2D = dylib.lookup<NativeFunction<TglSeparableFilter2D_Native>>('glSeparableFilter2D').asFunction();
    this.getSeparableFilter = dylib.lookup<NativeFunction<TglGetSeparableFilter_Native>>('glGetSeparableFilter').asFunction();
    this.activeTexture = dylib.lookup<NativeFunction<TglActiveTexture_Native>>('glActiveTexture').asFunction();
    this.clientActiveTexture = dylib.lookup<NativeFunction<TglClientActiveTexture_Native>>('glClientActiveTexture').asFunction();
    this.compressedTexImage1D = dylib.lookup<NativeFunction<TglCompressedTexImage1D_Native>>('glCompressedTexImage1D').asFunction();
    this.compressedTexImage2D = dylib.lookup<NativeFunction<TglCompressedTexImage2D_Native>>('glCompressedTexImage2D').asFunction();
    this.compressedTexImage3D = dylib.lookup<NativeFunction<TglCompressedTexImage3D_Native>>('glCompressedTexImage3D').asFunction();
    this.compressedTexSubImage1D = dylib.lookup<NativeFunction<TglCompressedTexSubImage1D_Native>>('glCompressedTexSubImage1D').asFunction();
    this.compressedTexSubImage2D = dylib.lookup<NativeFunction<TglCompressedTexSubImage2D_Native>>('glCompressedTexSubImage2D').asFunction();
    this.compressedTexSubImage3D = dylib.lookup<NativeFunction<TglCompressedTexSubImage3D_Native>>('glCompressedTexSubImage3D').asFunction();
    this.getCompressedTexImage = dylib.lookup<NativeFunction<TglGetCompressedTexImage_Native>>('glGetCompressedTexImage').asFunction();
    this.multiTexCoord1d = dylib.lookup<NativeFunction<TglMultiTexCoord1d_Native>>('glMultiTexCoord1d').asFunction();
    this.multiTexCoord1dv = dylib.lookup<NativeFunction<TglMultiTexCoord1dv_Native>>('glMultiTexCoord1dv').asFunction();
    this.multiTexCoord1f = dylib.lookup<NativeFunction<TglMultiTexCoord1f_Native>>('glMultiTexCoord1f').asFunction();
    this.multiTexCoord1fv = dylib.lookup<NativeFunction<TglMultiTexCoord1fv_Native>>('glMultiTexCoord1fv').asFunction();
    this.multiTexCoord1i = dylib.lookup<NativeFunction<TglMultiTexCoord1i_Native>>('glMultiTexCoord1i').asFunction();
    this.multiTexCoord1iv = dylib.lookup<NativeFunction<TglMultiTexCoord1iv_Native>>('glMultiTexCoord1iv').asFunction();
    this.multiTexCoord1s = dylib.lookup<NativeFunction<TglMultiTexCoord1s_Native>>('glMultiTexCoord1s').asFunction();
    this.multiTexCoord1sv = dylib.lookup<NativeFunction<TglMultiTexCoord1sv_Native>>('glMultiTexCoord1sv').asFunction();
    this.multiTexCoord2d = dylib.lookup<NativeFunction<TglMultiTexCoord2d_Native>>('glMultiTexCoord2d').asFunction();
    this.multiTexCoord2dv = dylib.lookup<NativeFunction<TglMultiTexCoord2dv_Native>>('glMultiTexCoord2dv').asFunction();
    this.multiTexCoord2f = dylib.lookup<NativeFunction<TglMultiTexCoord2f_Native>>('glMultiTexCoord2f').asFunction();
    this.multiTexCoord2fv = dylib.lookup<NativeFunction<TglMultiTexCoord2fv_Native>>('glMultiTexCoord2fv').asFunction();
    this.multiTexCoord2i = dylib.lookup<NativeFunction<TglMultiTexCoord2i_Native>>('glMultiTexCoord2i').asFunction();
    this.multiTexCoord2iv = dylib.lookup<NativeFunction<TglMultiTexCoord2iv_Native>>('glMultiTexCoord2iv').asFunction();
    this.multiTexCoord2s = dylib.lookup<NativeFunction<TglMultiTexCoord2s_Native>>('glMultiTexCoord2s').asFunction();
    this.multiTexCoord2sv = dylib.lookup<NativeFunction<TglMultiTexCoord2sv_Native>>('glMultiTexCoord2sv').asFunction();
    this.multiTexCoord3d = dylib.lookup<NativeFunction<TglMultiTexCoord3d_Native>>('glMultiTexCoord3d').asFunction();
    this.multiTexCoord3dv = dylib.lookup<NativeFunction<TglMultiTexCoord3dv_Native>>('glMultiTexCoord3dv').asFunction();
    this.multiTexCoord3f = dylib.lookup<NativeFunction<TglMultiTexCoord3f_Native>>('glMultiTexCoord3f').asFunction();
    this.multiTexCoord3fv = dylib.lookup<NativeFunction<TglMultiTexCoord3fv_Native>>('glMultiTexCoord3fv').asFunction();
    this.multiTexCoord3i = dylib.lookup<NativeFunction<TglMultiTexCoord3i_Native>>('glMultiTexCoord3i').asFunction();
    this.multiTexCoord3iv = dylib.lookup<NativeFunction<TglMultiTexCoord3iv_Native>>('glMultiTexCoord3iv').asFunction();
    this.multiTexCoord3s = dylib.lookup<NativeFunction<TglMultiTexCoord3s_Native>>('glMultiTexCoord3s').asFunction();
    this.multiTexCoord3sv = dylib.lookup<NativeFunction<TglMultiTexCoord3sv_Native>>('glMultiTexCoord3sv').asFunction();
    this.multiTexCoord4d = dylib.lookup<NativeFunction<TglMultiTexCoord4d_Native>>('glMultiTexCoord4d').asFunction();
    this.multiTexCoord4dv = dylib.lookup<NativeFunction<TglMultiTexCoord4dv_Native>>('glMultiTexCoord4dv').asFunction();
    this.multiTexCoord4f = dylib.lookup<NativeFunction<TglMultiTexCoord4f_Native>>('glMultiTexCoord4f').asFunction();
    this.multiTexCoord4fv = dylib.lookup<NativeFunction<TglMultiTexCoord4fv_Native>>('glMultiTexCoord4fv').asFunction();
    this.multiTexCoord4i = dylib.lookup<NativeFunction<TglMultiTexCoord4i_Native>>('glMultiTexCoord4i').asFunction();
    this.multiTexCoord4iv = dylib.lookup<NativeFunction<TglMultiTexCoord4iv_Native>>('glMultiTexCoord4iv').asFunction();
    this.multiTexCoord4s = dylib.lookup<NativeFunction<TglMultiTexCoord4s_Native>>('glMultiTexCoord4s').asFunction();
    this.multiTexCoord4sv = dylib.lookup<NativeFunction<TglMultiTexCoord4sv_Native>>('glMultiTexCoord4sv').asFunction();
    this.loadTransposeMatrixd = dylib.lookup<NativeFunction<TglLoadTransposeMatrixd_Native>>('glLoadTransposeMatrixd').asFunction();
    this.loadTransposeMatrixf = dylib.lookup<NativeFunction<TglLoadTransposeMatrixf_Native>>('glLoadTransposeMatrixf').asFunction();
    this.multTransposeMatrixd = dylib.lookup<NativeFunction<TglMultTransposeMatrixd_Native>>('glMultTransposeMatrixd').asFunction();
    this.multTransposeMatrixf = dylib.lookup<NativeFunction<TglMultTransposeMatrixf_Native>>('glMultTransposeMatrixf').asFunction();
    this.sampleCoverage = dylib.lookup<NativeFunction<TglSampleCoverage_Native>>('glSampleCoverage').asFunction();
    this.activeTextureARB = dylib.lookup<NativeFunction<TglActiveTextureARB_Native>>('glActiveTextureARB').asFunction();
    this.clientActiveTextureARB = dylib.lookup<NativeFunction<TglClientActiveTextureARB_Native>>('glClientActiveTextureARB').asFunction();
    this.multiTexCoord1dARB = dylib.lookup<NativeFunction<TglMultiTexCoord1dARB_Native>>('glMultiTexCoord1dARB').asFunction();
    this.multiTexCoord1dvARB = dylib.lookup<NativeFunction<TglMultiTexCoord1dvARB_Native>>('glMultiTexCoord1dvARB').asFunction();
    this.multiTexCoord1fARB = dylib.lookup<NativeFunction<TglMultiTexCoord1fARB_Native>>('glMultiTexCoord1fARB').asFunction();
    this.multiTexCoord1fvARB = dylib.lookup<NativeFunction<TglMultiTexCoord1fvARB_Native>>('glMultiTexCoord1fvARB').asFunction();
    this.multiTexCoord1iARB = dylib.lookup<NativeFunction<TglMultiTexCoord1iARB_Native>>('glMultiTexCoord1iARB').asFunction();
    this.multiTexCoord1ivARB = dylib.lookup<NativeFunction<TglMultiTexCoord1ivARB_Native>>('glMultiTexCoord1ivARB').asFunction();
    this.multiTexCoord1sARB = dylib.lookup<NativeFunction<TglMultiTexCoord1sARB_Native>>('glMultiTexCoord1sARB').asFunction();
    this.multiTexCoord1svARB = dylib.lookup<NativeFunction<TglMultiTexCoord1svARB_Native>>('glMultiTexCoord1svARB').asFunction();
    this.multiTexCoord2dARB = dylib.lookup<NativeFunction<TglMultiTexCoord2dARB_Native>>('glMultiTexCoord2dARB').asFunction();
    this.multiTexCoord2dvARB = dylib.lookup<NativeFunction<TglMultiTexCoord2dvARB_Native>>('glMultiTexCoord2dvARB').asFunction();
    this.multiTexCoord2fARB = dylib.lookup<NativeFunction<TglMultiTexCoord2fARB_Native>>('glMultiTexCoord2fARB').asFunction();
    this.multiTexCoord2fvARB = dylib.lookup<NativeFunction<TglMultiTexCoord2fvARB_Native>>('glMultiTexCoord2fvARB').asFunction();
    this.multiTexCoord2iARB = dylib.lookup<NativeFunction<TglMultiTexCoord2iARB_Native>>('glMultiTexCoord2iARB').asFunction();
    this.multiTexCoord2ivARB = dylib.lookup<NativeFunction<TglMultiTexCoord2ivARB_Native>>('glMultiTexCoord2ivARB').asFunction();
    this.multiTexCoord2sARB = dylib.lookup<NativeFunction<TglMultiTexCoord2sARB_Native>>('glMultiTexCoord2sARB').asFunction();
    this.multiTexCoord2svARB = dylib.lookup<NativeFunction<TglMultiTexCoord2svARB_Native>>('glMultiTexCoord2svARB').asFunction();
    this.multiTexCoord3dARB = dylib.lookup<NativeFunction<TglMultiTexCoord3dARB_Native>>('glMultiTexCoord3dARB').asFunction();
    this.multiTexCoord3dvARB = dylib.lookup<NativeFunction<TglMultiTexCoord3dvARB_Native>>('glMultiTexCoord3dvARB').asFunction();
    this.multiTexCoord3fARB = dylib.lookup<NativeFunction<TglMultiTexCoord3fARB_Native>>('glMultiTexCoord3fARB').asFunction();
    this.multiTexCoord3fvARB = dylib.lookup<NativeFunction<TglMultiTexCoord3fvARB_Native>>('glMultiTexCoord3fvARB').asFunction();
    this.multiTexCoord3iARB = dylib.lookup<NativeFunction<TglMultiTexCoord3iARB_Native>>('glMultiTexCoord3iARB').asFunction();
    this.multiTexCoord3ivARB = dylib.lookup<NativeFunction<TglMultiTexCoord3ivARB_Native>>('glMultiTexCoord3ivARB').asFunction();
    this.multiTexCoord3sARB = dylib.lookup<NativeFunction<TglMultiTexCoord3sARB_Native>>('glMultiTexCoord3sARB').asFunction();
    this.multiTexCoord3svARB = dylib.lookup<NativeFunction<TglMultiTexCoord3svARB_Native>>('glMultiTexCoord3svARB').asFunction();
    this.multiTexCoord4dARB = dylib.lookup<NativeFunction<TglMultiTexCoord4dARB_Native>>('glMultiTexCoord4dARB').asFunction();
    this.multiTexCoord4dvARB = dylib.lookup<NativeFunction<TglMultiTexCoord4dvARB_Native>>('glMultiTexCoord4dvARB').asFunction();
    this.multiTexCoord4fARB = dylib.lookup<NativeFunction<TglMultiTexCoord4fARB_Native>>('glMultiTexCoord4fARB').asFunction();
    this.multiTexCoord4fvARB = dylib.lookup<NativeFunction<TglMultiTexCoord4fvARB_Native>>('glMultiTexCoord4fvARB').asFunction();
    this.multiTexCoord4iARB = dylib.lookup<NativeFunction<TglMultiTexCoord4iARB_Native>>('glMultiTexCoord4iARB').asFunction();
    this.multiTexCoord4ivARB = dylib.lookup<NativeFunction<TglMultiTexCoord4ivARB_Native>>('glMultiTexCoord4ivARB').asFunction();
    this.multiTexCoord4sARB = dylib.lookup<NativeFunction<TglMultiTexCoord4sARB_Native>>('glMultiTexCoord4sARB').asFunction();
    this.multiTexCoord4svARB = dylib.lookup<NativeFunction<TglMultiTexCoord4svARB_Native>>('glMultiTexCoord4svARB').asFunction();
  }

  TglClearIndex_Func clearIndex;
  TglClearColor_Func clearColor;
  TglClear_Func clear;
  TglIndexMask_Func indexMask;
  TglColorMask_Func colorMask;
  TglAlphaFunc_Func alphaFunc;
  TglBlendFunc_Func blendFunc;
  TglLogicOp_Func logicOp;
  TglCullFace_Func cullFace;
  TglFrontFace_Func frontFace;
  TglPointSize_Func pointSize;
  TglLineWidth_Func lineWidth;
  TglLineStipple_Func lineStipple;
  TglPolygonMode_Func polygonMode;
  TglPolygonOffset_Func polygonOffset;
  TglPolygonStipple_Func polygonStipple;
  TglGetPolygonStipple_Func getPolygonStipple;
  TglEdgeFlag_Func edgeFlag;
  TglEdgeFlagv_Func edgeFlagv;
  TglScissor_Func scissor;
  TglClipPlane_Func clipPlane;
  TglGetClipPlane_Func getClipPlane;
  TglDrawBuffer_Func drawBuffer;
  TglReadBuffer_Func readBuffer;
  TglEnable_Func enable;
  TglDisable_Func disable;
  TglIsEnabled_Func isEnabled;
  TglEnableClientState_Func enableClientState;
  TglDisableClientState_Func disableClientState;
  TglGetBooleanv_Func getBooleanv;
  TglGetDoublev_Func getDoublev;
  TglGetFloatv_Func getFloatv;
  TglGetIntegerv_Func getIntegerv;
  TglPushAttrib_Func pushAttrib;
  TglPopAttrib_Func popAttrib;
  TglPushClientAttrib_Func pushClientAttrib;
  TglPopClientAttrib_Func popClientAttrib;
  TglRenderMode_Func renderMode;
  TglGetError_Func getError;
  TglGetString_Func getString;
  TglFinish_Func finish;
  TglFlush_Func flush;
  TglHint_Func hint;
  TglClearDepth_Func clearDepth;
  TglDepthFunc_Func depthFunc;
  TglDepthMask_Func depthMask;
  TglDepthRange_Func depthRange;
  TglClearAccum_Func clearAccum;
  TglAccum_Func accum;
  TglMatrixMode_Func matrixMode;
  TglOrtho_Func ortho;
  TglFrustum_Func frustum;
  TglViewport_Func viewport;
  TglPushMatrix_Func pushMatrix;
  TglPopMatrix_Func popMatrix;
  TglLoadIdentity_Func loadIdentity;
  TglLoadMatrixd_Func loadMatrixd;
  TglLoadMatrixf_Func loadMatrixf;
  TglMultMatrixd_Func multMatrixd;
  TglMultMatrixf_Func multMatrixf;
  TglRotated_Func rotated;
  TglRotatef_Func rotatef;
  TglScaled_Func scaled;
  TglScalef_Func scalef;
  TglTranslated_Func translated;
  TglTranslatef_Func translatef;
  TglIsList_Func isList;
  TglDeleteLists_Func deleteLists;
  TglGenLists_Func genLists;
  TglNewList_Func newList;
  TglEndList_Func endList;
  TglCallList_Func callList;
  TglCallLists_Func callLists;
  TglListBase_Func listBase;
  TglBegin_Func begin;
  TglEnd_Func end;
  TglVertex2d_Func vertex2d;
  TglVertex2f_Func vertex2f;
  TglVertex2i_Func vertex2i;
  TglVertex2s_Func vertex2s;
  TglVertex3d_Func vertex3d;
  TglVertex3f_Func vertex3f;
  TglVertex3i_Func vertex3i;
  TglVertex3s_Func vertex3s;
  TglVertex4d_Func vertex4d;
  TglVertex4f_Func vertex4f;
  TglVertex4i_Func vertex4i;
  TglVertex4s_Func vertex4s;
  TglVertex2dv_Func vertex2dv;
  TglVertex2fv_Func vertex2fv;
  TglVertex2iv_Func vertex2iv;
  TglVertex2sv_Func vertex2sv;
  TglVertex3dv_Func vertex3dv;
  TglVertex3fv_Func vertex3fv;
  TglVertex3iv_Func vertex3iv;
  TglVertex3sv_Func vertex3sv;
  TglVertex4dv_Func vertex4dv;
  TglVertex4fv_Func vertex4fv;
  TglVertex4iv_Func vertex4iv;
  TglVertex4sv_Func vertex4sv;
  TglNormal3b_Func normal3b;
  TglNormal3d_Func normal3d;
  TglNormal3f_Func normal3f;
  TglNormal3i_Func normal3i;
  TglNormal3s_Func normal3s;
  TglNormal3bv_Func normal3bv;
  TglNormal3dv_Func normal3dv;
  TglNormal3fv_Func normal3fv;
  TglNormal3iv_Func normal3iv;
  TglNormal3sv_Func normal3sv;
  TglIndexd_Func indexd;
  TglIndexf_Func indexf;
  TglIndexi_Func indexi;
  TglIndexs_Func indexs;
  TglIndexub_Func indexub;
  TglIndexdv_Func indexdv;
  TglIndexfv_Func indexfv;
  TglIndexiv_Func indexiv;
  TglIndexsv_Func indexsv;
  TglIndexubv_Func indexubv;
  TglColor3b_Func color3b;
  TglColor3d_Func color3d;
  TglColor3f_Func color3f;
  TglColor3i_Func color3i;
  TglColor3s_Func color3s;
  TglColor3ub_Func color3ub;
  TglColor3ui_Func color3ui;
  TglColor3us_Func color3us;
  TglColor4b_Func color4b;
  TglColor4d_Func color4d;
  TglColor4f_Func color4f;
  TglColor4i_Func color4i;
  TglColor4s_Func color4s;
  TglColor4ub_Func color4ub;
  TglColor4ui_Func color4ui;
  TglColor4us_Func color4us;
  TglColor3bv_Func color3bv;
  TglColor3dv_Func color3dv;
  TglColor3fv_Func color3fv;
  TglColor3iv_Func color3iv;
  TglColor3sv_Func color3sv;
  TglColor3ubv_Func color3ubv;
  TglColor3uiv_Func color3uiv;
  TglColor3usv_Func color3usv;
  TglColor4bv_Func color4bv;
  TglColor4dv_Func color4dv;
  TglColor4fv_Func color4fv;
  TglColor4iv_Func color4iv;
  TglColor4sv_Func color4sv;
  TglColor4ubv_Func color4ubv;
  TglColor4uiv_Func color4uiv;
  TglColor4usv_Func color4usv;
  TglTexCoord1d_Func texCoord1d;
  TglTexCoord1f_Func texCoord1f;
  TglTexCoord1i_Func texCoord1i;
  TglTexCoord1s_Func texCoord1s;
  TglTexCoord2d_Func texCoord2d;
  TglTexCoord2f_Func texCoord2f;
  TglTexCoord2i_Func texCoord2i;
  TglTexCoord2s_Func texCoord2s;
  TglTexCoord3d_Func texCoord3d;
  TglTexCoord3f_Func texCoord3f;
  TglTexCoord3i_Func texCoord3i;
  TglTexCoord3s_Func texCoord3s;
  TglTexCoord4d_Func texCoord4d;
  TglTexCoord4f_Func texCoord4f;
  TglTexCoord4i_Func texCoord4i;
  TglTexCoord4s_Func texCoord4s;
  TglTexCoord1dv_Func texCoord1dv;
  TglTexCoord1fv_Func texCoord1fv;
  TglTexCoord1iv_Func texCoord1iv;
  TglTexCoord1sv_Func texCoord1sv;
  TglTexCoord2dv_Func texCoord2dv;
  TglTexCoord2fv_Func texCoord2fv;
  TglTexCoord2iv_Func texCoord2iv;
  TglTexCoord2sv_Func texCoord2sv;
  TglTexCoord3dv_Func texCoord3dv;
  TglTexCoord3fv_Func texCoord3fv;
  TglTexCoord3iv_Func texCoord3iv;
  TglTexCoord3sv_Func texCoord3sv;
  TglTexCoord4dv_Func texCoord4dv;
  TglTexCoord4fv_Func texCoord4fv;
  TglTexCoord4iv_Func texCoord4iv;
  TglTexCoord4sv_Func texCoord4sv;
  TglRasterPos2d_Func rasterPos2d;
  TglRasterPos2f_Func rasterPos2f;
  TglRasterPos2i_Func rasterPos2i;
  TglRasterPos2s_Func rasterPos2s;
  TglRasterPos3d_Func rasterPos3d;
  TglRasterPos3f_Func rasterPos3f;
  TglRasterPos3i_Func rasterPos3i;
  TglRasterPos3s_Func rasterPos3s;
  TglRasterPos4d_Func rasterPos4d;
  TglRasterPos4f_Func rasterPos4f;
  TglRasterPos4i_Func rasterPos4i;
  TglRasterPos4s_Func rasterPos4s;
  TglRasterPos2dv_Func rasterPos2dv;
  TglRasterPos2fv_Func rasterPos2fv;
  TglRasterPos2iv_Func rasterPos2iv;
  TglRasterPos2sv_Func rasterPos2sv;
  TglRasterPos3dv_Func rasterPos3dv;
  TglRasterPos3fv_Func rasterPos3fv;
  TglRasterPos3iv_Func rasterPos3iv;
  TglRasterPos3sv_Func rasterPos3sv;
  TglRasterPos4dv_Func rasterPos4dv;
  TglRasterPos4fv_Func rasterPos4fv;
  TglRasterPos4iv_Func rasterPos4iv;
  TglRasterPos4sv_Func rasterPos4sv;
  TglRectd_Func rectd;
  TglRectf_Func rectf;
  TglRecti_Func recti;
  TglRects_Func rects;
  TglRectdv_Func rectdv;
  TglRectfv_Func rectfv;
  TglRectiv_Func rectiv;
  TglRectsv_Func rectsv;
  TglVertexPointer_Func vertexPointer;
  TglNormalPointer_Func normalPointer;
  TglColorPointer_Func colorPointer;
  TglIndexPointer_Func indexPointer;
  TglTexCoordPointer_Func texCoordPointer;
  TglEdgeFlagPointer_Func edgeFlagPointer;
  TglGetPointerv_Func getPointerv;
  TglArrayElement_Func arrayElement;
  TglDrawArrays_Func drawArrays;
  TglDrawElements_Func drawElements;
  TglInterleavedArrays_Func interleavedArrays;
  TglShadeModel_Func shadeModel;
  TglLightf_Func lightf;
  TglLighti_Func lighti;
  TglLightfv_Func lightfv;
  TglLightiv_Func lightiv;
  TglGetLightfv_Func getLightfv;
  TglGetLightiv_Func getLightiv;
  TglLightModelf_Func lightModelf;
  TglLightModeli_Func lightModeli;
  TglLightModelfv_Func lightModelfv;
  TglLightModeliv_Func lightModeliv;
  TglMaterialf_Func materialf;
  TglMateriali_Func materiali;
  TglMaterialfv_Func materialfv;
  TglMaterialiv_Func materialiv;
  TglGetMaterialfv_Func getMaterialfv;
  TglGetMaterialiv_Func getMaterialiv;
  TglColorMaterial_Func colorMaterial;
  TglPixelZoom_Func pixelZoom;
  TglPixelStoref_Func pixelStoref;
  TglPixelStorei_Func pixelStorei;
  TglPixelTransferf_Func pixelTransferf;
  TglPixelTransferi_Func pixelTransferi;
  TglPixelMapfv_Func pixelMapfv;
  TglPixelMapuiv_Func pixelMapuiv;
  TglPixelMapusv_Func pixelMapusv;
  TglGetPixelMapfv_Func getPixelMapfv;
  TglGetPixelMapuiv_Func getPixelMapuiv;
  TglGetPixelMapusv_Func getPixelMapusv;
  TglBitmap_Func bitmap;
  TglReadPixels_Func readPixels;
  TglDrawPixels_Func drawPixels;
  TglCopyPixels_Func copyPixels;
  TglStencilFunc_Func stencilFunc;
  TglStencilMask_Func stencilMask;
  TglStencilOp_Func stencilOp;
  TglClearStencil_Func clearStencil;
  TglTexGend_Func texGend;
  TglTexGenf_Func texGenf;
  TglTexGeni_Func texGeni;
  TglTexGendv_Func texGendv;
  TglTexGenfv_Func texGenfv;
  TglTexGeniv_Func texGeniv;
  TglGetTexGendv_Func getTexGendv;
  TglGetTexGenfv_Func getTexGenfv;
  TglGetTexGeniv_Func getTexGeniv;
  TglTexEnvf_Func texEnvf;
  TglTexEnvi_Func texEnvi;
  TglTexEnvfv_Func texEnvfv;
  TglTexEnviv_Func texEnviv;
  TglGetTexEnvfv_Func getTexEnvfv;
  TglGetTexEnviv_Func getTexEnviv;
  TglTexParameterf_Func texParameterf;
  TglTexParameteri_Func texParameteri;
  TglTexParameterfv_Func texParameterfv;
  TglTexParameteriv_Func texParameteriv;
  TglGetTexParameterfv_Func getTexParameterfv;
  TglGetTexParameteriv_Func getTexParameteriv;
  TglGetTexLevelParameterfv_Func getTexLevelParameterfv;
  TglGetTexLevelParameteriv_Func getTexLevelParameteriv;
  TglTexImage1D_Func texImage1D;
  TglTexImage2D_Func texImage2D;
  TglGetTexImage_Func getTexImage;
  TglGenTextures_Func genTextures;
  TglDeleteTextures_Func deleteTextures;
  TglBindTexture_Func bindTexture;
  TglPrioritizeTextures_Func prioritizeTextures;
  TglAreTexturesResident_Func areTexturesResident;
  TglIsTexture_Func isTexture;
  TglTexSubImage1D_Func texSubImage1D;
  TglTexSubImage2D_Func texSubImage2D;
  TglCopyTexImage1D_Func copyTexImage1D;
  TglCopyTexImage2D_Func copyTexImage2D;
  TglCopyTexSubImage1D_Func copyTexSubImage1D;
  TglCopyTexSubImage2D_Func copyTexSubImage2D;
  TglMap1d_Func map1d;
  TglMap1f_Func map1f;
  TglMap2d_Func map2d;
  TglMap2f_Func map2f;
  TglGetMapdv_Func getMapdv;
  TglGetMapfv_Func getMapfv;
  TglGetMapiv_Func getMapiv;
  TglEvalCoord1d_Func evalCoord1d;
  TglEvalCoord1f_Func evalCoord1f;
  TglEvalCoord1dv_Func evalCoord1dv;
  TglEvalCoord1fv_Func evalCoord1fv;
  TglEvalCoord2d_Func evalCoord2d;
  TglEvalCoord2f_Func evalCoord2f;
  TglEvalCoord2dv_Func evalCoord2dv;
  TglEvalCoord2fv_Func evalCoord2fv;
  TglMapGrid1d_Func mapGrid1d;
  TglMapGrid1f_Func mapGrid1f;
  TglMapGrid2d_Func mapGrid2d;
  TglMapGrid2f_Func mapGrid2f;
  TglEvalPoint1_Func evalPoint1;
  TglEvalPoint2_Func evalPoint2;
  TglEvalMesh1_Func evalMesh1;
  TglEvalMesh2_Func evalMesh2;
  TglFogf_Func fogf;
  TglFogi_Func fogi;
  TglFogfv_Func fogfv;
  TglFogiv_Func fogiv;
  TglFeedbackBuffer_Func feedbackBuffer;
  TglPassThrough_Func passThrough;
  TglSelectBuffer_Func selectBuffer;
  TglInitNames_Func initNames;
  TglLoadName_Func loadName;
  TglPushName_Func pushName;
  TglPopName_Func popName;
  TglDrawRangeElements_Func drawRangeElements;
  TglTexImage3D_Func texImage3D;
  TglTexSubImage3D_Func texSubImage3D;
  TglCopyTexSubImage3D_Func copyTexSubImage3D;
  TglColorTable_Func colorTable;
  TglColorSubTable_Func colorSubTable;
  TglColorTableParameteriv_Func colorTableParameteriv;
  TglColorTableParameterfv_Func colorTableParameterfv;
  TglCopyColorSubTable_Func copyColorSubTable;
  TglCopyColorTable_Func copyColorTable;
  TglGetColorTable_Func getColorTable;
  TglGetColorTableParameterfv_Func getColorTableParameterfv;
  TglGetColorTableParameteriv_Func getColorTableParameteriv;
  TglBlendEquation_Func blendEquation;
  TglBlendColor_Func blendColor;
  TglHistogram_Func histogram;
  TglResetHistogram_Func resetHistogram;
  TglGetHistogram_Func getHistogram;
  TglGetHistogramParameterfv_Func getHistogramParameterfv;
  TglGetHistogramParameteriv_Func getHistogramParameteriv;
  TglMinmax_Func minmax;
  TglResetMinmax_Func resetMinmax;
  TglGetMinmax_Func getMinmax;
  TglGetMinmaxParameterfv_Func getMinmaxParameterfv;
  TglGetMinmaxParameteriv_Func getMinmaxParameteriv;
  TglConvolutionFilter1D_Func convolutionFilter1D;
  TglConvolutionFilter2D_Func convolutionFilter2D;
  TglConvolutionParameterf_Func convolutionParameterf;
  TglConvolutionParameterfv_Func convolutionParameterfv;
  TglConvolutionParameteri_Func convolutionParameteri;
  TglConvolutionParameteriv_Func convolutionParameteriv;
  TglCopyConvolutionFilter1D_Func copyConvolutionFilter1D;
  TglCopyConvolutionFilter2D_Func copyConvolutionFilter2D;
  TglGetConvolutionFilter_Func getConvolutionFilter;
  TglGetConvolutionParameterfv_Func getConvolutionParameterfv;
  TglGetConvolutionParameteriv_Func getConvolutionParameteriv;
  TglSeparableFilter2D_Func separableFilter2D;
  TglGetSeparableFilter_Func getSeparableFilter;
  TglActiveTexture_Func activeTexture;
  TglClientActiveTexture_Func clientActiveTexture;
  TglCompressedTexImage1D_Func compressedTexImage1D;
  TglCompressedTexImage2D_Func compressedTexImage2D;
  TglCompressedTexImage3D_Func compressedTexImage3D;
  TglCompressedTexSubImage1D_Func compressedTexSubImage1D;
  TglCompressedTexSubImage2D_Func compressedTexSubImage2D;
  TglCompressedTexSubImage3D_Func compressedTexSubImage3D;
  TglGetCompressedTexImage_Func getCompressedTexImage;
  TglMultiTexCoord1d_Func multiTexCoord1d;
  TglMultiTexCoord1dv_Func multiTexCoord1dv;
  TglMultiTexCoord1f_Func multiTexCoord1f;
  TglMultiTexCoord1fv_Func multiTexCoord1fv;
  TglMultiTexCoord1i_Func multiTexCoord1i;
  TglMultiTexCoord1iv_Func multiTexCoord1iv;
  TglMultiTexCoord1s_Func multiTexCoord1s;
  TglMultiTexCoord1sv_Func multiTexCoord1sv;
  TglMultiTexCoord2d_Func multiTexCoord2d;
  TglMultiTexCoord2dv_Func multiTexCoord2dv;
  TglMultiTexCoord2f_Func multiTexCoord2f;
  TglMultiTexCoord2fv_Func multiTexCoord2fv;
  TglMultiTexCoord2i_Func multiTexCoord2i;
  TglMultiTexCoord2iv_Func multiTexCoord2iv;
  TglMultiTexCoord2s_Func multiTexCoord2s;
  TglMultiTexCoord2sv_Func multiTexCoord2sv;
  TglMultiTexCoord3d_Func multiTexCoord3d;
  TglMultiTexCoord3dv_Func multiTexCoord3dv;
  TglMultiTexCoord3f_Func multiTexCoord3f;
  TglMultiTexCoord3fv_Func multiTexCoord3fv;
  TglMultiTexCoord3i_Func multiTexCoord3i;
  TglMultiTexCoord3iv_Func multiTexCoord3iv;
  TglMultiTexCoord3s_Func multiTexCoord3s;
  TglMultiTexCoord3sv_Func multiTexCoord3sv;
  TglMultiTexCoord4d_Func multiTexCoord4d;
  TglMultiTexCoord4dv_Func multiTexCoord4dv;
  TglMultiTexCoord4f_Func multiTexCoord4f;
  TglMultiTexCoord4fv_Func multiTexCoord4fv;
  TglMultiTexCoord4i_Func multiTexCoord4i;
  TglMultiTexCoord4iv_Func multiTexCoord4iv;
  TglMultiTexCoord4s_Func multiTexCoord4s;
  TglMultiTexCoord4sv_Func multiTexCoord4sv;
  TglLoadTransposeMatrixd_Func loadTransposeMatrixd;
  TglLoadTransposeMatrixf_Func loadTransposeMatrixf;
  TglMultTransposeMatrixd_Func multTransposeMatrixd;
  TglMultTransposeMatrixf_Func multTransposeMatrixf;
  TglSampleCoverage_Func sampleCoverage;
  TglActiveTextureARB_Func activeTextureARB;
  TglClientActiveTextureARB_Func clientActiveTextureARB;
  TglMultiTexCoord1dARB_Func multiTexCoord1dARB;
  TglMultiTexCoord1dvARB_Func multiTexCoord1dvARB;
  TglMultiTexCoord1fARB_Func multiTexCoord1fARB;
  TglMultiTexCoord1fvARB_Func multiTexCoord1fvARB;
  TglMultiTexCoord1iARB_Func multiTexCoord1iARB;
  TglMultiTexCoord1ivARB_Func multiTexCoord1ivARB;
  TglMultiTexCoord1sARB_Func multiTexCoord1sARB;
  TglMultiTexCoord1svARB_Func multiTexCoord1svARB;
  TglMultiTexCoord2dARB_Func multiTexCoord2dARB;
  TglMultiTexCoord2dvARB_Func multiTexCoord2dvARB;
  TglMultiTexCoord2fARB_Func multiTexCoord2fARB;
  TglMultiTexCoord2fvARB_Func multiTexCoord2fvARB;
  TglMultiTexCoord2iARB_Func multiTexCoord2iARB;
  TglMultiTexCoord2ivARB_Func multiTexCoord2ivARB;
  TglMultiTexCoord2sARB_Func multiTexCoord2sARB;
  TglMultiTexCoord2svARB_Func multiTexCoord2svARB;
  TglMultiTexCoord3dARB_Func multiTexCoord3dARB;
  TglMultiTexCoord3dvARB_Func multiTexCoord3dvARB;
  TglMultiTexCoord3fARB_Func multiTexCoord3fARB;
  TglMultiTexCoord3fvARB_Func multiTexCoord3fvARB;
  TglMultiTexCoord3iARB_Func multiTexCoord3iARB;
  TglMultiTexCoord3ivARB_Func multiTexCoord3ivARB;
  TglMultiTexCoord3sARB_Func multiTexCoord3sARB;
  TglMultiTexCoord3svARB_Func multiTexCoord3svARB;
  TglMultiTexCoord4dARB_Func multiTexCoord4dARB;
  TglMultiTexCoord4dvARB_Func multiTexCoord4dvARB;
  TglMultiTexCoord4fARB_Func multiTexCoord4fARB;
  TglMultiTexCoord4fvARB_Func multiTexCoord4fvARB;
  TglMultiTexCoord4iARB_Func multiTexCoord4iARB;
  TglMultiTexCoord4ivARB_Func multiTexCoord4ivARB;
  TglMultiTexCoord4sARB_Func multiTexCoord4sARB;
  TglMultiTexCoord4svARB_Func multiTexCoord4svARB;
}
